name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
    - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
    
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dimasabiyoga/order-service:latest
      
    - name: docker push
      run: docker push dimasabiyoga/order-service:latest
